# Generated by Django 5.2.3 on 2025-07-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0003_author_tag_authorprofile_comment_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(related_name="product", to="store_app.tag"),
        ),
    ]
