# Generated by Django 5.2.3 on 2025-07-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0005_alter_product_category_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
